version: '3'

services:
  db:
    image: postgres:15.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: hospitaldb
    volumes:
      - ./postgres:/var/lib/postgresql/data
